#pragma once
#include "camera.hpp"
#include "comptime.hpp"
#include "globals.hpp"
#include "materials.hpp"
#include "math.hpp"
#include "sphere.hpp"
#include "types.hpp"
#include <SDL2/SDL.h>
#include <array>
#include <chrono>
#include <cstdint>
#include <cstdio>
#include <future>
#include <immintrin.h>
#define STB_IMAGE_WRITE_IMPLEMENTATION
#include "utils.hpp"
#include <stb_image_write.h>
// TODO what is this file used for? Seems unnecessary.
